### ISSUE TITLE
[meta] Implementation status

### ISSUE THREAD

**Issue by jplatte** [fest-im/fest#16]
If you find something is missing on this list, ping me on [#fest-im:matrix.org](https://matrix.to/#/#fest-im:matrix.org).

* [ ] Log in
  * [ ] As guest
  * [ ] With an account
* [ ] Specify a custom homeserver
* [ ] Register a new account
* [ ] Display user information
* [ ] Application settings
* [ ] User settings
* [ ] Display room directory
* [ ] Display user's joined rooms
  * [ ] Grouping
* [ ] **Inside of chat rooms**
  * [ ] Display events
    * [ ] As they come in
    * [ ] From the server history
    * [ ] Text messages
    * [ ] File attachments
    * [ ] Profile updates
  * [ ] Send events
    * [ ] Text messages
    * [ ] File attachments
    * [ ] Profile updates
  * [ ] Typing notifications
    * [ ] Send
    * [ ] Receive / Display
  * [ ] Room settings
